### ISSUE TITLE
error

### ISSUE THREAD

**Issue by CHETHAN562** [StableCanvas/StableCanvas#1]

**Comment by zhzLuke96** [comment]
What do you error? please provide details, such as
 - error content output in the console
- or pop-up content

**Comment by CHETHAN562** [comment]
--api --cors-allow-origins=https://beta.stablecanvas.com              --api --cors-allow-origins="https://beta.stablecanvas.com"



![Screenshot_20230225_113806](https://user-images.githubusercontent.com/72523729/221407332-d684e286-7c6b-48f2-b351-c1303b829835.png)
 can you guide how to use  how to connect auto111 to canvas

**Comment by zhzLuke96** [comment]
> --api --cors-allow-origins=https://beta.stablecanvas.com --api --cors-allow-origins="https://beta.stablecanvas.com"
> 
> ![Screenshot_20230225_113806](https://user-images.githubusercontent.com/72523729/221407332-d684e286-7c6b-48f2-b351-c1303b829835.png) can you guide how to use how to connect auto111 to canvas when I try to use it always freezes in canvas

Are you using a webui running locally?
- Is it possible to use webui with https://localhost:7860
- Then make sure to execute the webui with `--api` and `--cors-allow-origins="https://beta.stablecanvas.com"`

If you still can't connect to canvas, please check chrome devtools and provide me with error message for further investigation

**Comment by zhzLuke96** [comment]
okey...I think this problem should be solved now, you can try again, it should not be your problem

By the way, in order to achieve the best experience, please use the `latest version of chrome (or edge)`
