### ISSUE TITLE
[Feature] I'd like to run this locally

### ISSUE THREAD

**Issue by phazei** [StableCanvas/StableCanvas#4]
Since I'm running my models locally, any tool I'd use I'd expect to be local as well.  Is this available  to run locally?  It looks quite awesome.  Basically an interface similar to InvokeAI, but without Invoke's extremely limited ability to run any model.

**Comment by zhzLuke96** [comment]
Thank you for your interest in this (somewhat niche) project~ 😇

Unfortunately, I have to tell you that this project is closed-source and cannot currently run locally.  
That said, you can still use your locally deployed models through APIs. At the moment, we primarily support the a1111/webui interface (ComfyUI is also supported, but its setup can be a bit tricky).

One unfortunate piece of news is that this project is currently unmaintained, with many features (including local model support) still left unfinished. 😥

**Suggestion:**  
For your need for a more comprehensive and easy-to-use local model solution, I recommend trying **Krita + ComfyUI**. Some of the ideas in this project were inspired by that workflow, and it might be what you're looking for. Plus, both the Krita and ComfyUI communities are very active.  
You can find more details here: https://github.com/Acly/krita-ai-diffusion

**Comment by phazei** [comment]
Hope it gets finished sometime, I've my share of projects I've never completed, heh.  Thanks for the suggestion, Krita does look pretty cool.
